-- TS - AI Ideas Hub — Core Competency, Junior (P2) tier seed
--
-- Adds the Junior Specialist (P2 / "Applied") tier of Skedulo TS's career
-- ladder to the existing Core Competency track (see core-competency-seed.sql,
-- which seeded the Intern/P1 slice only — this file is the "later level's
-- own content" that file's own header anticipated). Source: "TS Career
-- Track - Learning Plan Master.xlsx", the same 12 competency tabs as before,
-- now carrying the full P1-P5 ladder — this file imports only the rows
-- marked Level = 'Applied' (Role = 'Junior Specialist'). Quiz questions come
-- from "Quizzes - Intern + Junior.xlsx", matched the same way
-- core-competency-seed.sql matches its own quiz content: by each tab's own
-- "Source: URL" line against courses.link, not tab or title text alone.
--
-- Not a new track: Junior is a tier within the existing Core Competency
-- track, the same way the AI Track already spans intern through principal
-- in one track row. No `tracks` insert here — Core Competency already
-- exists (core-competency-seed.sql). stage is 'L1 — Applied', continuing
-- Core Competency's own stage-per-tier labelling from 'L0 — Foundations'
-- (Intern), the same L0/L1/L2/L3 pattern the AI Track already uses.
--
-- 17 of the master spreadsheet's own 'Applied' rows exist across the 12
-- tabs; only 12 land here as new courses. The other 5 repeat, verbatim, a
-- title already seeded at the Intern tier in core-competency-seed.sql — the
-- source spreadsheet lists these as reading that stays relevant into the
-- Junior tier, not a new resource. Since courses' natural key is
-- (track_id, title), a second row for the same title is neither possible
-- nor needed: the existing Intern-tier row already covers it, and this
-- file's ON CONFLICT DO NOTHING leaves it untouched if a stray attempt to
-- re-add it is ever made. The 5: 'Shared Ticketing Process – Skedulo &
-- Lumary' (Process and Procedures), 'GraphQL (Skedulo Pulse Platform)'
-- (Tools and Systems), 'Incident Analysis Report (Aug 2025–Aug 2026) —
-- severity mix, detection methods, trends' (Incident Mgmt & Escalation),
-- 'TED — Vernā Myers: How to overcome our biases? Walk boldly toward them'
-- (Culture Champion), and 'TED — Yves Morieux: How too many rules at work
-- keep you from getting things done' (Performance Excellence). Their quiz
-- tabs in the Junior workbook (PP-03, TS-03, IE-04, CUL-03, PEX-03) are
-- excluded for the same reason: the course_id they'd attach to already has
-- a full quiz from the Intern import, and (course_id, position) would
-- collide on the very same position numbers.
--
-- Not destructive to run — every insert here is ON CONFLICT DO NOTHING,
-- safe to re-run on a database that already has some or all of this
-- content. The skills UPDATE is re-runnable for a different reason (plain
-- UPDATE, not an insert) — same pattern as core-competency-seed.sql.
--
-- Run schema.sql and core-competency-seed.sql first (this depends on the
-- Core Competency track and its Intern-tier courses already existing).

-- 12 real resources — see file header for the 5 excluded (already seeded
-- at the Intern tier). roadmap_order continues Core Competency's own
-- sequence (Intern used 1-36), numbered in the same tab-then-row order as
-- the source spreadsheet, skipping the 5 already-numbered duplicates.
insert into courses (track_id, stage, focus_area, title, platform, priority, est_hours, cost, outcome, expected_by_position, link, roadmap_order)
select (select id from tracks where name = 'Core Competency'), v.*
from (values
  ('L1 — Applied', 'Troubleshooting', 'Technical Communication: Speak the Language of Business', 'Free - Udemy', 'core', 4.0, 'Free - Udemy', 'Explains a technical root cause or fix to non-technical stakeholders — customers, leadership — in plain, jargon-free language using a repeatable 5-part message structure.', 'junior', 'https://skedulo.udemy.com/course/communication-for-technical-professionals/', 37),
  ('L1 — Applied', 'Troubleshooting', 'Root Cause Analysis', 'Free - Udemy', 'optional', 1.0, 'Free - Udemy', 'Works a structured 5-whys or fishbone analysis on a recurring bug before escalating.', 'junior', 'https://skedulo.udemy.com/course/root-cause-analysis-i/', 38),
  ('L1 — Applied', 'Custom vs Core', 'Customize and extend Skedulo web app', 'docs.skedulo.com', 'core', 4.0, 'Free (internal)', 'Designs custom objects/fields, overrides default pages, and builds custom list views and web extensions for the Skedulo web app using the CLI-based workflow.', 'junior', 'https://docs.skedulo.com/developer-guides/customize-and-extend/', 39),
  ('L1 — Applied', 'Custom vs Core', 'Customize and extend Skedulo mobile apps', 'docs.skedulo.com', 'core', 3.5, 'Free (internal)', 'Builds a custom mobile page for the Skedulo Plus app — including offline-capable forms, GraphQL data, and localisation — and deploys it via the Skedulo CLI.', 'junior', 'https://docs.skedulo.com/developer-guides/customize-and-extend-mobile/', 40),
  ('L1 — Applied', 'Tools and Systems', 'Admin Console', 'Internal', 'core', 0.5, 'Free (internal)', 'Finds a customer/team record in the Admin Console, reads a team''s region/datastore/login setup, checks or explains what a feature flag (GA, Beta, Alpha) does for a tenant, and runs the standard fix for a team stuck on "uninitialized_tenant" (Reset team + re-enter the Salesforce org ID).', 'junior', 'https://docs.google.com/presentation/d/1yW8gsJBxNDtO9QZ3W_gQDxmbhNhHhjLTJ3epUK0QrlM/edit?usp=sharing', 41),
  ('L1 — Applied', 'SLAs and Deliverables', 'SLAs in Jira Service Management (Skillbuilder course)', 'Atlassian University', 'core', 1.0, 'Free', 'Reads and applies an SLA policy in JSM and explains breach risk to a customer before it happens.', 'junior', 'https://enable.atlassian.com/student/activity/817163-slas-in-jira-service-management-asb-412-course-description', 42),
  ('L1 — Applied', 'Growth and Learning', 'TED — Angela Duckworth: Grit — the power of passion and perseverance', 'TED', 'core', 0.15, 'Free', 'Builds a personal development plan and sticks with a hard skill through a plateau.', 'junior', 'https://www.ted.com/talks/angela_lee_duckworth_grit_the_power_of_passion_and_perseverance', 43),
  ('L1 — Applied', 'Growth and Learning', 'How to Learn: Effective Approaches for Self-Guided Learning', 'Free - Udemy', 'optional', 1.5, 'Free - Udemy', 'Sets a concrete goal before starting a course and applies a practice-reflect-repeat cycle so a new technical skill actually sticks.', 'junior', 'https://skedulo.udemy.com/course/how-to-learn-effective-approaches-for-self-guided-learning/', 44),
  ('L1 — Applied', 'Cross-Functional Collaboration', 'TED — Julian Treasure: How to speak so that people want to listen', 'TED', 'core', 0.1, 'Free', 'Adjusts tone and framing so a cross-functional update lands with a non-technical audience.', 'junior', 'https://www.ted.com/talks/julian_treasure_how_to_speak_so_that_people_want_to_listen', 45),
  ('L1 — Applied', 'Performance Excellence', 'Time Management Mastery', 'Free - Udemy', 'core', 2.0, 'Free - Udemy', 'Manages a full ticket queue independently, prioritising the highest-value work first.', 'junior', 'https://skedulo.udemy.com/course/do-more-stress-less/', 46),
  ('L1 — Applied', 'Change Driver & Innovator', 'TED — Kare Anderson: Be an opportunity maker', 'TED', 'core', 0.13, 'Free', 'Turns an observed inefficiency into a small, self-run experiment with a defined outcome.', 'junior', 'https://www.ted.com/talks/kare_anderson_be_an_opportunity_maker', 47),
  ('L1 — Applied', 'Customer First mindset', 'Customer Service, Customer Support, And Customer Experience', 'Free - Udemy', 'optional', 5.0, 'Free - Udemy', 'Turns an angry or frustrated customer interaction into a positive one using empathy-based de-escalation and positive language.', 'junior', 'https://skedulo.udemy.com/course/how-to-find-your-voice-the-resonates-with-your-customers/', 48)
) as v(stage, focus_area, title, platform, priority, est_hours, cost, outcome, expected_by_position, link, roadmap_order)
on conflict (track_id, title) do nothing;

-- Skill tags (courses.skills) for the 12 new courses, mapped onto Core
-- Competency's existing 8-skill taxonomy (core-competency-seed.sql) — no
-- new skill needed, every one of these 12 fits an existing tag. Same
-- re-runnable UPDATE-by-title pattern as that file, scoped to this track by
-- title + track_id.
update courses set skills = v.skills
from (values
  ('Technical Communication: Speak the Language of Business', array['Technical Troubleshooting']::text[]),
  ('Root Cause Analysis', array['Technical Troubleshooting']::text[]),
  ('Customize and extend Skedulo web app', array['Skedulo Pulse Platform Fundamentals']::text[]),
  ('Customize and extend Skedulo mobile apps', array['Skedulo Pulse Platform Fundamentals']::text[]),
  ('Admin Console', array['Support Tooling & Systems']::text[]),
  ('SLAs in Jira Service Management (Skillbuilder course)', array['Support Process & SLAs']::text[]),
  ('TED — Angela Duckworth: Grit — the power of passion and perseverance', array['Growth Mindset & Feedback Culture']::text[]),
  ('How to Learn: Effective Approaches for Self-Guided Learning', array['Growth Mindset & Feedback Culture']::text[]),
  ('TED — Julian Treasure: How to speak so that people want to listen', array['Customer-Centered Communication']::text[]),
  ('Time Management Mastery', array['Performance & Innovation']::text[]),
  ('TED — Kare Anderson: Be an opportunity maker', array['Performance & Innovation']::text[]),
  ('Customer Service, Customer Support, And Customer Experience', array['Customer-Centered Communication']::text[])
) as v(title, skills)
where courses.title = v.title
  and courses.track_id = (select id from tracks where name = 'Core Competency');

-- Wrap-up quiz content — 120 questions across the 12 new courses (10
-- each), imported from "Quizzes - Intern + Junior.xlsx"'s own 'Applied —
-- Junior Specialist' tabs, matched to courses by title, cross-checked
-- against each tab's own "Source: URL" line against courses.link — same
-- pattern as core-competency-seed.sql's own quiz insert. `options` is a
-- jsonb array (`[{"label":"A","text":"..."}, ...]`, always 4 options,
-- A-D). One tab (TS-04 "Admin Console") recorded its own Correct Answer
-- column as the full option text rather than a bare letter; normalized to
-- the bare label on the way in, same as every other row, since
-- course_quiz_questions.correct_answer must be one of options[].label.
insert into course_quiz_questions (course_id, position, question, options, correct_answer, rationale)
select c.id, v.position, v.question, v.options, v.correct_answer, v.rationale
from (values
  ('Technical Communication: Speak the Language of Business', 1, 'What is the core premise of this course, per its own description?', '[{"label": "A", "text": "Technical skill alone is what makes professionals progress fastest"}, {"label": "B", "text": "Technical expertise solves problems, but communication skill is what helps other people understand, support, approve, and act on your ideas"}, {"label": "C", "text": "Non-technical audiences should be avoided rather than communicated with"}, {"label": "D", "text": "Jargon is necessary to establish credibility with executives"}]'::jsonb, 'B', 'The course explicitly frames communication as the differentiator for career progress, separate from (and additive to) technical expertise.'),
  ('Technical Communication: Speak the Language of Business', 2, 'How many parts does the course''s core communication framework have?', '[{"label": "A", "text": "3"}, {"label": "B", "text": "5"}, {"label": "C", "text": "7"}, {"label": "D", "text": "10"}]'::jsonb, 'B', 'The curriculum is structured around a 5-part framework: Audience, Relevant, Relatable, Simple, and Jargon-free.'),
  ('Technical Communication: Speak the Language of Business', 3, 'What does the "Relevant" part of the framework focus on?', '[{"label": "A", "text": "Making the message as long and detailed as possible"}, {"label": "B", "text": "Showing the audience why they should care about the message"}, {"label": "C", "text": "Listing every technical detail of the underlying system"}, {"label": "D", "text": "Matching the speaker''s own vocabulary preferences"}]'::jsonb, 'B', 'Per the course''s curriculum breakdown, "Relevant" is specifically about establishing why the topic matters to the listener.'),
  ('Technical Communication: Speak the Language of Business', 4, 'What does the "Simple" part of the framework cover?', '[{"label": "A", "text": "A single trick for shortening emails"}, {"label": "B", "text": "11 different ways to simplify a message"}, {"label": "C", "text": "A rule to never use more than 5 words per sentence"}, {"label": "D", "text": "Formatting slides with fewer colors"}]'::jsonb, 'B', 'The course curriculum lists "Part 4: Simple" as covering 11 distinct ways to simplify a message.'),
  ('Technical Communication: Speak the Language of Business', 5, 'According to the course description, what common complaint from business stakeholders is this course meant to fix?', '[{"label": "A", "text": "Being told to \"keep it higher level\" or \"be more strategic\" and watching stakeholders lose interest mid-explanation"}, {"label": "B", "text": "Complaints that presentations are too short"}, {"label": "C", "text": "Requests for more jargon and technical acronyms"}, {"label": "D", "text": "Complaints that meetings start too early"}]'::jsonb, 'A', 'The course description opens with these exact frustrations as the motivating problem it addresses.'),
  ('Technical Communication: Speak the Language of Business', 6, 'What does the "Audience" part of the framework ask the speaker to do first?', '[{"label": "A", "text": "Decide on the audience''s point of view before crafting the message"}, {"label": "B", "text": "Choose which slide template to use"}, {"label": "C", "text": "Determine how long the talk should be, regardless of listener"}, {"label": "D", "text": "Pick a joke to open with"}]'::jsonb, 'A', 'Per the curriculum, "Part 1: Audience" is specifically about understanding the audience''s point of view as the starting point of the framework.'),
  ('Technical Communication: Speak the Language of Business', 7, 'A support engineer is drafting a root-cause explanation for a non-technical customer contact and starts with, "The issue was a race condition in the async job dispatcher''s mutex lock." Which part of the framework is most clearly being skipped?', '[{"label": "A", "text": "Audience — the explanation isn''t adapted to a non-technical listener''s point of view"}, {"label": "B", "text": "Relevant — because race conditions are always relevant"}, {"label": "C", "text": "Simple — this sentence is already simple enough"}, {"label": "D", "text": "None; this is the correct way to explain a technical root cause"}]'::jsonb, 'A', 'Leading with unexplained technical jargon for a non-technical audience skips the "Audience" step of adapting the message to the listener''s point of view, and also skips "Jargon-free."'),
  ('Technical Communication: Speak the Language of Business', 8, 'A junior engineer wants executive buy-in for a fix that requires a costly infrastructure change. Per the course''s "Relevant" principle, what should the pitch emphasize first?', '[{"label": "A", "text": "A full history of every technical decision that led to the current state"}, {"label": "B", "text": "Why the change matters to the business outcomes executives care about, before the technical implementation details"}, {"label": "C", "text": "The names of every internal system involved"}, {"label": "D", "text": "A list of all other tickets related to this issue"}]'::jsonb, 'B', 'The "Relevant" step is specifically about establishing why the audience (here, executives) should care, before diving into supporting detail.'),
  ('Technical Communication: Speak the Language of Business', 9, 'A support agent''s status update to a non-technical stakeholder is accurate but full of internal acronyms (e.g., "SLA breach on P1 via DevRev-to-Linear pipeline"). Which part of the 5-part framework does this violate, and what''s the fix?', '[{"label": "A", "text": "Jargon-free — the fix is to translate acronyms into plain language the audience already understands"}, {"label": "B", "text": "Audience — the fix is to make the message longer"}, {"label": "C", "text": "Relatable — the fix is to add more acronyms for precision"}, {"label": "D", "text": "This doesn''t violate any part of the framework since it''s technically accurate"}]'::jsonb, 'A', 'The course explicitly targets jargon as one of the common problems it corrects, with "Jargon-free" as one of the five framework parts.'),
  ('Technical Communication: Speak the Language of Business', 10, 'A support agent needs to explain a complex outage to two different audiences: the engineering team and an anxious customer executive. Per the framework, should the message be identical for both?', '[{"label": "A", "text": "Yes, one identical technical message is always best for consistency"}, {"label": "B", "text": "No — the \"Audience\" step means adapting the message to each group''s point of view and vocabulary, even if the underlying facts are the same"}, {"label": "C", "text": "No — the facts themselves should be changed depending on the audience"}, {"label": "D", "text": "Yes, because adapting the message would be dishonest"}]'::jsonb, 'B', 'The framework''s "Audience" principle is about adapting presentation and framing to different audiences'' viewpoints, not changing the underlying facts.'),
  ('Root Cause Analysis', 1, 'What is the core purpose of Root Cause Analysis (RCA), per the course?', '[{"label": "A", "text": "To quickly assign blame to a team member"}, {"label": "B", "text": "To dig past surface symptoms to find the underlying reason a problem occurred, rather than just patching visible effects"}, {"label": "C", "text": "To skip investigation and go straight to a fix"}, {"label": "D", "text": "To document a problem without acting on it"}]'::jsonb, 'B', 'The course frames RCA as understanding how problems and points of failure arise from underlying details, not just observed symptoms.'),
  ('Root Cause Analysis', 2, 'What is the "5 Whys" technique?', '[{"label": "A", "text": "Asking \"why\" repeatedly (typically five times) to a problem statement to drill down from a symptom to its underlying cause"}, {"label": "B", "text": "A checklist of five unrelated troubleshooting questions asked once"}, {"label": "C", "text": "A technique for prioritizing which five tickets to work on first"}, {"label": "D", "text": "A rule requiring five different engineers to review a fix"}]'::jsonb, 'A', 'The course lists "Explain the 5 Why''s Technique" as a core learning objective, which is the standard iterative-questioning method for tracing a symptom back to its root cause.'),
  ('Root Cause Analysis', 3, 'What is a Fishbone (Ishikawa) diagram used for, in the context of this course?', '[{"label": "A", "text": "Scheduling shifts for a support team"}, {"label": "B", "text": "Visually organizing potential causes of a problem into categories to identify the root cause"}, {"label": "C", "text": "Tracking customer satisfaction scores over time"}, {"label": "D", "text": "Displaying a project''s Gantt chart"}]'::jsonb, 'B', 'The course lists "Explain the Steps to Create Fishbone Diagram" as a technique for categorizing and visualizing potential causes of a problem.'),
  ('Root Cause Analysis', 4, 'What does Pareto Analysis help identify, per the course''s learning objectives?', '[{"label": "A", "text": "The exact code line that caused a bug"}, {"label": "B", "text": "Which few causes are responsible for the majority of a problem''s impact (the \"80/20\" idea)"}, {"label": "C", "text": "A customer''s billing history"}, {"label": "D", "text": "The fastest way to close a ticket regardless of cause"}]'::jsonb, 'B', 'Pareto Analysis (from the course''s objectives) is about identifying the vital few contributing factors that account for most of a problem''s impact.'),
  ('Root Cause Analysis', 5, 'What does the course identify as a key difficulty in conducting RCA?', '[{"label": "A", "text": "RCA is difficult because it requires no data collection at all"}, {"label": "B", "text": "The course explicitly lists difficulties in RCA as a learning objective, implying real investigations often face obstacles like incomplete information or interconnected variables"}, {"label": "C", "text": "RCA has no known difficulties according to the course"}, {"label": "D", "text": "RCA can only be performed by senior engineers"}]'::jsonb, 'B', '"List the Difficulties in RCA" is one of the course''s explicit learning objectives, reflecting that real-world root cause work is often harder than the clean technique implies.'),
  ('Root Cause Analysis', 6, 'Per the course description, why is RCA described as valuable for highlighting issues "long before they result in catastrophic failure"?', '[{"label": "A", "text": "Because RCA is only useful after a catastrophic failure has already occurred"}, {"label": "B", "text": "Because RCA trains you to notice how small, easily-overlooked details relate to bigger downstream failures"}, {"label": "C", "text": "Because RCA eliminates the need for any monitoring systems"}, {"label": "D", "text": "Because RCA is primarily a financial audit technique"}]'::jsonb, 'B', 'The course description emphasizes that problems, errors, and failure points often arise from small details being missed — RCA is presented as a way to catch these earlier.'),
  ('Root Cause Analysis', 7, 'A recurring bug keeps getting patched at the point where it''s noticed, but keeps resurfacing in slightly different forms. What would the course''s RCA approach suggest doing differently?', '[{"label": "A", "text": "Keep patching the same visible symptom each time it appears"}, {"label": "B", "text": "Apply a technique like the 5 Whys or a Fishbone diagram to trace the recurring symptom back to a shared underlying cause, rather than treating each occurrence as new"}, {"label": "C", "text": "Close the ticket as \"won''t fix\" since it keeps recurring"}, {"label": "D", "text": "Escalate immediately without any internal investigation"}]'::jsonb, 'B', 'This is exactly the scenario RCA is designed for — a recurring symptom suggests an unaddressed root cause, which the 5 Whys or Fishbone method is meant to surface.'),
  ('Root Cause Analysis', 8, 'A support engineer collects data on the last 50 customer-reported bugs and wants to know which handful of causes account for most of them, to prioritize the biggest wins. Which technique from the course fits this need best?', '[{"label": "A", "text": "The 5 Whys, since it''s designed for aggregate statistical analysis"}, {"label": "B", "text": "Pareto Analysis, since it''s specifically about identifying which few causes drive most of the impact"}, {"label": "C", "text": "A Fishbone diagram, since it only works for single incidents"}, {"label": "D", "text": "None of the course''s techniques apply to aggregate data"}]'::jsonb, 'B', 'Pareto Analysis is the technique aimed at identifying the small number of causes responsible for the majority of observed problems, which matches this prioritization scenario.'),
  ('Root Cause Analysis', 9, 'A junior engineer proposes a root cause for an outage after a single, quick guess with no supporting investigation. Based on the course''s framing of RCA, what is the risk?', '[{"label": "A", "text": "There is no risk — quick guesses are equivalent to structured RCA"}, {"label": "B", "text": "Skipping structured techniques (5 Whys, Fishbone, Pareto) risks fixing the wrong underlying cause, since seemingly unconnected variables often relate to one another in ways a quick guess would miss"}, {"label": "C", "text": "RCA is only for post-mortems, not for outages"}, {"label": "D", "text": "This is the correct application of RCA"}]'::jsonb, 'B', 'The course specifically frames RCA''s value as understanding how seemingly unconnected variables relate to each other — something a snap judgment, without the structured techniques, is likely to miss.'),
  ('Root Cause Analysis', 10, 'Why does the course emphasize communicating RCA findings "with clarity to a broad audience" as a key skill?', '[{"label": "A", "text": "Because RCA findings are only ever relevant to the engineer who did the analysis"}, {"label": "B", "text": "Because the value of identifying a root cause is lost if stakeholders across different backgrounds can''t understand and act on the finding"}, {"label": "C", "text": "Because RCA reports are legally required to be public"}, {"label": "D", "text": "Clarity of communication is not mentioned in the course"}]'::jsonb, 'B', 'The course lists communicating findings clearly to a broad audience as a specific benefit/skill, since an unshared or misunderstood root cause can''t drive the right fix or prevention.'),
  ('Customize and extend Skedulo web app', 1, 'What is the difference between a "Lookup" and a "Has-many" custom field type?', '[{"label": "A", "text": "They are two names for the same relationship type"}, {"label": "B", "text": "A Lookup field creates a one-to-one/many-to-one relationship to another object, while a Has-many field establishes a one-to-many relationship"}, {"label": "C", "text": "Lookup fields only work with picklists, Has-many fields only work with text fields"}, {"label": "D", "text": "Has-many fields can only be created via the API, never in the UI"}]'::jsonb, 'B', 'The docs define Lookup as a reference to a single related record, and Has-many as the relational field type used to model one-to-many relationships between objects.'),
  ('Customize and extend Skedulo web app', 2, 'What are the two ways documented for creating a custom object and fields in the Skedulo Pulse Platform?', '[{"label": "A", "text": "Only via a third-party integration tool"}, {"label": "B", "text": "Programmatically via the Skedulo API, or through the UI-based tools in the Pulse Platform (form builders/field configuration)"}, {"label": "C", "text": "Only by contacting Skedulo support directly"}, {"label": "D", "text": "Only through Salesforce, never natively in Skedulo"}]'::jsonb, 'B', 'The docs cover both an API-driven approach (for automation/pipelines) and a UI-driven approach (for non-developers) to create custom objects and fields.'),
  ('Customize and extend Skedulo web app', 3, 'What is a "picklist dependency" in Skedulo''s custom field documentation?', '[{"label": "A", "text": "A rule that deletes a picklist if it''s unused for 90 days"}, {"label": "B", "text": "Conditional logic where a field''s visibility or available options change based on the value selected in a parent field"}, {"label": "C", "text": "A requirement that picklists must depend on an external database"}, {"label": "D", "text": "A setting that locks a picklist''s options so they can never be edited"}]'::jsonb, 'B', 'Field dependencies let one picklist''s shown options (or the field''s visibility) change based on what was selected in a related parent field.'),
  ('Customize and extend Skedulo web app', 4, 'Why does the documentation recommend using the Skedulo CLI over the Skedulo Packages SDK?', '[{"label": "A", "text": "The SDK was never released publicly"}, {"label": "B", "text": "The SDK has been deprecated, and the CLI is the current, recommended tool for developing customizations"}, {"label": "C", "text": "The CLI can only be used for mobile extensions, not the web app"}, {"label": "D", "text": "There is no CLI available; SDK is still the primary tool"}]'::jsonb, 'B', 'The docs explicitly state the Packages SDK is deprecated in favor of the CLI for developing customizations.'),
  ('Customize and extend Skedulo web app', 5, 'What does "overriding a system-generated page" let a developer do?', '[{"label": "A", "text": "Only change the page''s color scheme"}, {"label": "B", "text": "Replace one of Skedulo''s built-in Create, View, Edit, or List pages for an object with a custom-built version, for full UI control"}, {"label": "C", "text": "Permanently delete the object the page is tied to"}, {"label": "D", "text": "Change page overrides only for Salesforce-native objects"}]'::jsonb, 'B', 'The docs describe overriding system pages as replacing the default Create/View/Edit/List pages with custom versions built from Horizon and Breeze components.'),
  ('Customize and extend Skedulo web app', 6, 'What are Horizon and Breeze, as referenced in the page-building documentation?', '[{"label": "A", "text": "Two competing external analytics platforms"}, {"label": "B", "text": "Component libraries/frameworks used to build and lay out custom pages within Skedulo"}, {"label": "C", "text": "Names of Skedulo''s mobile and desktop apps"}, {"label": "D", "text": "Data storage engines used internally by Skedulo"}]'::jsonb, 'B', 'The docs reference Horizon and Breeze components as the toolkit for constructing custom pages, including overridden system pages and list views.'),
  ('Customize and extend Skedulo web app', 7, 'A support engineer needs to help a customer who wants a custom "Equipment" object where each Equipment record can be linked to many Job records. Which field type should link Equipment to its many related Jobs?', '[{"label": "A", "text": "A Lookup field on the Equipment object"}, {"label": "B", "text": "A Has-many field, since the relationship is one Equipment record to many Job records"}, {"label": "C", "text": "A picklist field with the Job names hardcoded as options"}, {"label": "D", "text": "This isn''t possible without a custom object override"}]'::jsonb, 'B', 'A one-to-many relationship (one Equipment linked to many Jobs) is exactly what a Has-many field is designed to model, per the docs'' distinction from Lookup.'),
  ('Customize and extend Skedulo web app', 8, 'A customer reports that after customizing a picklist, a dependent field is now permanently hidden regardless of the parent value chosen. What''s the most likely area to investigate first, based on this documentation?', '[{"label": "A", "text": "The GraphQL API rate limits"}, {"label": "B", "text": "The field dependency configuration linking that field''s visibility to the parent picklist''s selected value"}, {"label": "C", "text": "The Skedulo CLI installation on the customer''s machine"}, {"label": "D", "text": "The mobile app''s offline cache"}]'::jsonb, 'B', 'Since field dependencies specifically control conditional visibility based on a parent picklist value, a misconfigured dependency is the most direct place to check for this symptom.'),
  ('Customize and extend Skedulo web app', 9, 'A customer built a fully custom, standalone web page extension a few years ago and asks if that''s still the recommended approach for new work. Based on the docs, what should you tell them?', '[{"label": "A", "text": "Yes, standalone web extensions are the current best-practice approach for all new pages"}, {"label": "B", "text": "That pattern (along with embedded and multi-page web extensions) is documented as deprecated; new development should use the CLI-based approach and Horizon-based pages instead"}, {"label": "C", "text": "Standalone extensions were removed entirely and no longer function at all"}, {"label": "D", "text": "Standalone extensions are only for mobile, not web"}]'::jsonb, 'B', 'The docs mark standalone, embedded, and multi-page web extensions as deprecated patterns superseded by CLI-based, component-driven development.'),
  ('Customize and extend Skedulo web app', 10, 'A customer wants their list view to show a computed, styled column (e.g., a colored status badge) rather than a plain field value. Which documented capability supports this?', '[{"label": "A", "text": "Basic column sorting only"}, {"label": "B", "text": "Advanced column configuration / column templates, which support formatting, conditional rendering, and computed columns"}, {"label": "C", "text": "This requires modifying the underlying database directly"}, {"label": "D", "text": "This is only possible by overriding the entire List page from scratch"}]'::jsonb, 'B', 'The docs describe advanced column configuration and column templates as supporting exactly this kind of formatted, conditional, or computed column display in list views.'),
  ('Customize and extend Skedulo mobile apps', 1, 'What is a Skedulo Plus extension?', '[{"label": "A", "text": "A paid add-on that unlocks more storage in the web app"}, {"label": "B", "text": "A custom mobile page view built for the Skedulo Plus mobile application"}, {"label": "C", "text": "A browser plugin for the Skedulo web app"}, {"label": "D", "text": "A third-party app unrelated to Skedulo''s own mobile app"}]'::jsonb, 'B', 'The docs define Skedulo Plus extensions as the mechanism for building custom page views specifically within the Skedulo Plus mobile app.'),
  ('Customize and extend Skedulo mobile apps', 2, 'What is the main difference between a "flat page" and a "list page" in the extension page types?', '[{"label": "A", "text": "Flat pages only display images; list pages only display text"}, {"label": "B", "text": "A flat page is a general-purpose, form-style layout, while a list page is specialized for displaying collections of items with selection/filtering/navigation"}, {"label": "C", "text": "There is no functional difference; the names are interchangeable"}, {"label": "D", "text": "List pages only work offline; flat pages only work online"}]'::jsonb, 'B', 'The docs distinguish flat pages (general form-based layout components) from list pages (built specifically for browsing and interacting with collections of records).'),
  ('Customize and extend Skedulo mobile apps', 3, 'What is GraphQL used for within a Skedulo Plus extension?', '[{"label": "A", "text": "Styling the extension''s visual theme"}, {"label": "B", "text": "Fetching live, instance-specific data from the backend to populate the extension''s forms or lists"}, {"label": "C", "text": "Only for sending push notifications"}, {"label": "D", "text": "Compiling the extension into a mobile app binary"}]'::jsonb, 'B', 'The docs describe GraphQL data fetching as how an extension pulls live backend data (as opposed to static, pre-bundled data) to populate its UI.'),
  ('Customize and extend Skedulo mobile apps', 4, 'What does "online/offline mode handling" let a developer configure in an extension?', '[{"label": "A", "text": "Which language the extension displays in"}, {"label": "B", "text": "Restricting certain features to only work when the device has connectivity, while other parts remain usable offline"}, {"label": "C", "text": "Whether the extension appears in the app''s main menu"}, {"label": "D", "text": "The extension''s file size limit"}]'::jsonb, 'B', 'The docs describe this capability specifically as controlling which parts of a form or extension require an active connection versus working offline.'),
  ('Customize and extend Skedulo mobile apps', 5, 'Which of these is listed as a component available in the mobile extension component library?', '[{"label": "A", "text": "Signature capture, for capturing handwritten signatures such as work confirmations"}, {"label": "B", "text": "A built-in payment processor"}, {"label": "C", "text": "A video conferencing widget"}, {"label": "D", "text": "A spreadsheet formula engine"}]'::jsonb, 'A', 'Signature capture is explicitly listed among the extension component library''s UI elements, used for confirmations and approvals in the field.'),
  ('Customize and extend Skedulo mobile apps', 6, 'What does the "Image Annotation" component allow a mobile user to do?', '[{"label": "A", "text": "Automatically categorize photos using AI with no user input"}, {"label": "B", "text": "Capture a photo and add visual markup, such as highlighting or arrows, for field documentation"}, {"label": "C", "text": "Compress images to save storage space"}, {"label": "D", "text": "Convert images into PDF documents"}]'::jsonb, 'B', 'The docs describe Image Annotation as enabling a field worker to mark up a captured photo — e.g., highlighting or pointing at an issue — as part of documentation.'),
  ('Customize and extend Skedulo mobile apps', 7, 'A customer wants a mobile extension where a resource selects a job from a scrollable, filterable set of records, then taps one to see details. Which page type should the extension use as its foundation?', '[{"label": "A", "text": "A flat page, since it displays a single record''s data"}, {"label": "B", "text": "A list page, since it''s designed specifically for browsing and selecting among a collection of records"}, {"label": "C", "text": "Neither — this requires a native mobile app build, not an extension"}, {"label": "D", "text": "A Section component alone, without any page type"}]'::jsonb, 'B', 'Browsing and selecting among a collection of records with filtering is exactly the scenario the docs describe list pages as built for, versus a flat page''s general form layout.'),
  ('Customize and extend Skedulo mobile apps', 8, 'A field technician needs to fill out a job-completion form, but their vehicle is often in areas with no signal. A customer asks if the form can still be partially usable without connectivity. Based on the docs, how would you frame the answer?', '[{"label": "A", "text": "All Skedulo Plus extensions require a live connection at all times, with no offline option"}, {"label": "B", "text": "Online/offline mode handling lets the extension''s fields be configured so that only the parts genuinely requiring connectivity are restricted, while the rest of the form remains usable offline"}, {"label": "C", "text": "Offline support is only available on iOS devices, never Android"}, {"label": "D", "text": "The technician would need to switch to the older, non-Plus mobile app to get offline support"}]'::jsonb, 'B', 'This directly matches the documented online/offline mode handling capability, which is designed for exactly this kind of intermittent-connectivity field scenario.'),
  ('Customize and extend Skedulo mobile apps', 9, 'A customer wants the extension to pre-populate a list of standard equipment types without hitting the network every time the form loads. Which documented mechanism fits this need best?', '[{"label": "A", "text": "GraphQL data fetching, since it always requires a live network call"}, {"label": "B", "text": "Static data fetching, which allows pre-bundled data to be included directly in the extension package"}, {"label": "C", "text": "Image annotation, repurposed to store a list"}, {"label": "D", "text": "This isn''t supported; all data must come from a live query"}]'::jsonb, 'B', 'The docs describe static data fetching as the complement to GraphQL specifically for data that can be pre-bundled with the extension rather than queried live.'),
  ('Customize and extend Skedulo mobile apps', 10, 'A customer''s extension needs to show the same labels in both English and Spanish depending on the field worker''s device settings. Which documented feature supports this?', '[{"label": "A", "text": "Custom functions"}, {"label": "B", "text": "Resource localization, which supports multi-language extensions through localized static resources"}, {"label": "C", "text": "Validation rules"}, {"label": "D", "text": "The Toggle component"}]'::jsonb, 'B', 'Resource localization is specifically documented as the mechanism for supporting multiple languages via localized static resources in an extension.'),
  ('Admin Console', 1, 'What is the Admin Console, and who is it for?', '[{"label": "A", "text": "An internal-only Skedulo tool for creating and configuring web-app teams and their feature flags, used by internal staff only"}, {"label": "B", "text": "A customer-facing dashboard for tracking their own usage stats"}, {"label": "C", "text": "A public tool anyone can sign up for at admin-console.skedulo.com"}, {"label": "D", "text": "A ticketing system used by the Technical Support team"}]'::jsonb, 'A', 'The deck defines the Admin Console as an internal-only tool for creating/configuring teams (both Skedulo Pulse Platform and Skedulo for Salesforce) and their feature flags — never customer-facing.'),
  ('Admin Console', 2, 'In Admin Console terminology, what is the relationship between a Customer and a Team?', '[{"label": "A", "text": "One customer can have many teams"}, {"label": "B", "text": "One team can belong to many customers"}, {"label": "C", "text": "Customer and Team are the same record type"}, {"label": "D", "text": "Teams exist independently of any customer"}]'::jsonb, 'A', 'A Customer is the paying organisation; a Team is one instance of the web app for that customer (e.g., separate prod, dev, UAT, and test teams) — so one customer commonly has several teams.'),
  ('Admin Console', 3, 'What is a team''s datastore (also called the tenant)?', '[{"label": "A", "text": "Where the team''s config and data live — a Skedulo database for Pulse teams, or a Salesforce org for Skedulo for Salesforce teams"}, {"label": "B", "text": "A backup copy of the team''s records kept for disaster recovery"}, {"label": "C", "text": "The Slack channel used to support that customer"}, {"label": "D", "text": "The list of feature flags enabled for a team"}]'::jsonb, 'A', 'The datastore/tenant is 1:1 with the team: for Pulse Platform teams it is a Skedulo database, and for Skedulo for Salesforce teams it is the Salesforce org itself.'),
  ('Admin Console', 4, 'A Skedulo for Salesforce customer''s team is set to the AU region, but their Salesforce org''s Skedulo_API_Server record still points to the default endpoint. What symptom is this likely to cause?', '[{"label": "A", "text": "An authentication error such as \"Could not find a valid authentication method for this token\" when API tokens are used"}, {"label": "B", "text": "The team''s URL silently redirects to the US datastore"}, {"label": "C", "text": "Feature flags reset to their defaults every 24 hours"}, {"label": "D", "text": "No issue — region only affects data residency, not API calls"}]'::jsonb, 'A', 'AU/UK-region Skedulo for Salesforce teams must have the Skedulo_API_Server custom metadata record updated to the matching regional endpoint (api.au.skedulo.com or api.uk.skedulo.com); otherwise API tokens fail with this exact authentication error.'),
  ('Admin Console', 5, 'Where would a support engineer find a Skedulo for Salesforce team''s Tenant ID (the Salesforce 18-character org ID)?', '[{"label": "A", "text": "In the customer''s Salesforce org, under Setup → Company Information"}, {"label": "B", "text": "In the team''s mobile app settings"}, {"label": "C", "text": "In the customer''s DevRev ticket history"}, {"label": "D", "text": "It cannot be retrieved once the team is created"}]'::jsonb, 'A', 'The deck states the Tenant ID for Skedulo for Salesforce teams is the Salesforce 18-character org ID, found in the customer''s Salesforce org under Setup → Company Information.'),
  ('Admin Console', 6, 'A customer reports a blank screen on first login, and the browser console shows an "uninitialized_tenant" error. What is the documented fix?', '[{"label": "A", "text": "In the Admin Console, open the team, select Reset team, and re-enter the customer''s Salesforce 18-character org ID"}, {"label": "B", "text": "Ask the customer to clear their browser cache and try again"}, {"label": "C", "text": "Disable the enablePlatformUI flag for that team"}, {"label": "D", "text": "Escalate directly to Engineering as a Sub-Issue"}]'::jsonb, 'A', 'This is called out as the most-asked support question for the Admin Console — the fix is to Reset team and re-enter the (18-character, converted from 15 if needed) Salesforce org ID from Setup → Company Information → Organization ID.'),
  ('Admin Console', 7, 'What are the four categories used to classify feature flags in the Admin Console?', '[{"label": "A", "text": "General Availability, Beta, Alpha, and Other (development/internal/deprecated)"}, {"label": "B", "text": "Core, Optional, Preview, and Legacy"}, {"label": "C", "text": "Enabled, Disabled, Pending, and Removed"}, {"label": "D", "text": "Platform, Salesforce, Mobile, and Web"}]'::jsonb, 'A', 'The deck defines four flag categories: GA (stable, fully implemented), Beta (customer-available but may be unstable), Alpha (preview, selected customers only), and Other (development, internal, or deprecated flags).'),
  ('Admin Console', 8, 'A customer''s admin enables enablePlatformUI and useNewPermissions, but custom roles still aren''t taking effect and the nav menu looks unchanged. What''s the most likely explanation, and where should support check the affected user''s access?', '[{"label": "A", "text": "Web app menu configs must be migrated to the new menu after enablePlatformUI is enabled (not automatic), and useNewPermissions depends on enablePlatformUI working correctly — check the user''s role in Settings → Permissions"}, {"label": "B", "text": "useNewPermissions doesn''t actually depend on enablePlatformUI, so something unrelated must be broken"}, {"label": "C", "text": "Custom roles only work on Skedulo for Salesforce teams"}, {"label": "D", "text": "The two flags conflict and can never both be enabled at once"}]'::jsonb, 'A', 'enablePlatformUI requires a manual menu migration and useNewPermissions depends on it; the documented support playbook for ''user can''t see records after a role change'' is to confirm both flags are enabled and then verify the custom role in Settings → Permissions.'),
  ('Admin Console', 9, 'A customer migrated from the legacy web app to Skedulo Plus and reports their custom forms are missing. Which flag should support consider, and is it a permanent fix?', '[{"label": "A", "text": "enableV2FormsInV3 — no, it is a temporary bridge until the forms are rebuilt on MEX"}, {"label": "B", "text": "useOptimization — yes, this permanently resolves missing forms"}, {"label": "C", "text": "enableV3MobileApp — yes, this is the permanent solution"}, {"label": "D", "text": "useMessaging — no feature flag affects forms"}]'::jsonb, 'A', 'enableV2FormsInV3 is explicitly described as a temporary bridge that shows legacy V2 forms inside Skedulo Plus; the real fix is rebuilding those forms on MEX, coordinated with the CSM and mobile team.'),
  ('Admin Console', 10, 'A customer wants the Offers tab removed entirely from their mobile app. Which flags need to be addressed?', '[{"label": "A", "text": "Both useJobOffers and useShiftOffers must be disabled"}, {"label": "B", "text": "Only useOptimization needs to be disabled"}, {"label": "C", "text": "Disabling useSuggestions alone removes the Offers tab"}, {"label": "D", "text": "The Offers tab cannot be removed once enabled"}]'::jsonb, 'A', 'The deck notes that useJobOffers off alone only stops the Offers tab from rendering job offers — to remove the Offers tab entirely, both useJobOffers and useShiftOffers must be turned off.'),
  ('SLAs in Jira Service Management (Skillbuilder course)', 1, 'What are the two primary SLA metrics tracked in Jira Service Management?', '[{"label": "A", "text": "Time-to-first-response and time-to-resolution"}, {"label": "B", "text": "Ticket count and customer satisfaction score"}, {"label": "C", "text": "Agent headcount and average handle time"}, {"label": "D", "text": "Escalation count and reopen rate"}]'::jsonb, 'A', 'JSM''s SLA system is built around these two core timers: how fast an agent first responds, and how fast the request is fully resolved.'),
  ('SLAs in Jira Service Management (Skillbuilder course)', 2, 'What does an SLA "calendar" control?', '[{"label": "A", "text": "Which agents are allowed to work on a ticket"}, {"label": "B", "text": "The active business hours/working periods counted toward an SLA goal''s duration, excluding non-working hours, weekends, or holidays"}, {"label": "C", "text": "The customer''s time zone display preference only"}, {"label": "D", "text": "How many tickets an agent can be assigned per day"}]'::jsonb, 'B', 'Calendars define which hours actually count toward the SLA clock, so time outside business hours (nights, weekends, holidays) doesn''t count against the goal.'),
  ('SLAs in Jira Service Management (Skillbuilder course)', 3, 'What are the three conditions that govern an SLA''s clock?', '[{"label": "A", "text": "Create, Update, Delete"}, {"label": "B", "text": "Start, Pause, and Stop conditions"}, {"label": "C", "text": "Open, Escalate, Close"}, {"label": "D", "text": "Trigger, Notify, Archive"}]'::jsonb, 'B', 'Start conditions begin the clock, Pause conditions temporarily suspend it (e.g. while waiting on the customer), and Stop conditions end it permanently once the goal is met.'),
  ('SLAs in Jira Service Management (Skillbuilder course)', 4, 'How does JSM visually indicate that an SLA goal has been breached?', '[{"label": "A", "text": "It sends an email to the customer automatically with no visual indicator"}, {"label": "B", "text": "The remaining/elapsed time is shown highlighted in red, versus standard formatting for on-track goals"}, {"label": "C", "text": "The ticket is automatically closed"}, {"label": "D", "text": "There is no visual indicator; you must query the database"}]'::jsonb, 'B', 'JSM surfaces breach status directly on the ticket through red highlighting of the SLA time indicator, distinct from the normal display for goals still on track.'),
  ('SLAs in Jira Service Management (Skillbuilder course)', 5, 'Per Atlassian''s troubleshooting guidance, what can happen to SLA timing when a ticket''s priority changes mid-flight (a "goal shift")?', '[{"label": "A", "text": "SLA timing is unaffected by priority changes"}, {"label": "B", "text": "Prior elapsed time carries over to the new goal, which can cause the ticket to appear breached even if the team acted appropriately given the original priority"}, {"label": "C", "text": "The SLA clock automatically resets to zero"}, {"label": "D", "text": "The ticket is deleted and a new one is created"}]'::jsonb, 'B', 'Atlassian''s troubleshooting docs specifically flag this as a source of confusing breaches: time already accrued under the old goal carries forward when the goal changes.'),
  ('SLAs in Jira Service Management (Skillbuilder course)', 6, 'What does Atlassian recommend when SLA values look stale or incorrect on open/resolved issues?', '[{"label": "A", "text": "Deleting and recreating the project"}, {"label": "B", "text": "Performing an SLA recalculation (e.g. by editing and saving an existing SLA), noting this affects open/resolved issues rather than historical data"}, {"label": "C", "text": "Reinstalling Jira Service Management entirely"}, {"label": "D", "text": "Waiting 30 days for the cache to clear automatically"}]'::jsonb, 'B', 'The troubleshooting docs describe SLA recalculation via an edit-and-save action as the standard fix for stale SLA display, with the caveat that it doesn''t rewrite historical records.'),
  ('SLAs in Jira Service Management (Skillbuilder course)', 7, 'A customer asks why their urgent ticket''s SLA clock didn''t move for several hours overnight. What''s the most likely, non-bug explanation, based on how calendars work?', '[{"label": "A", "text": "The SLA calendar excludes non-business hours, so the clock correctly paused/didn''t accrue time outside the configured working period"}, {"label": "B", "text": "SLAs are decorative and never actually track real time"}, {"label": "C", "text": "The ticket must have been deleted and recreated"}, {"label": "D", "text": "Overnight hours always count double toward SLA goals"}]'::jsonb, 'A', 'Since SLA calendars define active business hours, a clock appearing to "not move" overnight is normal behavior if the calendar excludes those hours, not necessarily a fault.'),
  ('SLAs in Jira Service Management (Skillbuilder course)', 8, 'A ticket was originally logged as Low priority, then escalated to Critical after 20 hours. The customer is surprised the SLA now shows as breached almost immediately after escalation. Using the "goal shift" concept, how would you explain this to the customer?', '[{"label": "A", "text": "This is definitely a system bug that needs an engineering fix before any explanation is given"}, {"label": "B", "text": "The 20 hours already elapsed under the original Low-priority goal carried over into the new, shorter Critical-priority goal, causing it to show as breached almost immediately — this is expected goal-shift behavior, not necessarily a service failure"}, {"label": "C", "text": "SLA breaches are always caused by agent negligence"}, {"label": "D", "text": "The SLA timer restarts at zero whenever priority changes, so there''s no way it could show a breach this fast"}]'::jsonb, 'B', 'This is a direct application of the goal-shift behavior Atlassian documents: carried-over elapsed time under a new, stricter goal can trigger an apparent breach that reflects timer mechanics, not necessarily poor service.'),
  ('SLAs in Jira Service Management (Skillbuilder course)', 9, 'A junior agent wants to warn a customer proactively before an SLA breaches, rather than explaining it after the fact. Based on how SLA goals and remaining-time indicators work, what should they check first?', '[{"label": "A", "text": "The ticket''s SLA remaining-time indicator and goal duration, to see how close the ticket is to its configured goal before it turns red/breaches"}, {"label": "B", "text": "The customer''s billing history"}, {"label": "C", "text": "Whether the customer has submitted tickets before"}, {"label": "D", "text": "The agent''s own performance review score"}]'::jsonb, 'A', 'Since JSM surfaces remaining time toward the goal directly on the ticket, checking that indicator before it flips to breached is the direct way to proactively flag risk to a customer.'),
  ('SLAs in Jira Service Management (Skillbuilder course)', 10, 'A team lead notices SLA configuration pages are timing out and loading slowly. Per Atlassian''s troubleshooting guidance, what is a likely cause?', '[{"label": "A", "text": "The customer''s internet connection"}, {"label": "B", "text": "An excessive number of SLA rules combined with intricate JQL conditions, which can exceed processing time limits on large instances"}, {"label": "C", "text": "The support agent''s laptop needs more RAM"}, {"label": "D", "text": "SLA pages never load slowly; this would indicate total outage"}]'::jsonb, 'B', 'Atlassian''s troubleshooting docs specifically identify high rule counts and complex JQL as a cause of slow-loading or hanging SLA configuration screens.'),
  ('TED — Angela Duckworth: Grit — the power of passion and perseverance', 1, 'How does Duckworth define "grit"?', '[{"label": "A", "text": "Natural talent combined with a high IQ"}, {"label": "B", "text": "Passion and perseverance for very long-term goals — sustained effort over years, not just a short burst"}, {"label": "C", "text": "The willingness to work more hours than anyone else in a single week"}, {"label": "D", "text": "A fixed personality trait present from birth that cannot change"}]'::jsonb, 'B', 'Duckworth is explicit that grit is about stamina over the long term — "living life like it''s a marathon, not a sprint" — not raw talent or short-term intensity.'),
  ('TED — Angela Duckworth: Grit — the power of passion and perseverance', 2, 'What originally led Duckworth to study grit, based on her time teaching seventh-grade math?', '[{"label": "A", "text": "She noticed IQ alone didn''t explain why some high-IQ students underperformed while some less naturally gifted students excelled"}, {"label": "B", "text": "She wanted to design a better standardized test"}, {"label": "C", "text": "All her students performed exactly as their IQ scores predicted"}, {"label": "D", "text": "She was asked by the school board to study teacher salaries"}]'::jsonb, 'A', 'This mismatch between raw ability and actual outcomes is what pushed Duckworth to look for a psychological factor — grit — beyond IQ.'),
  ('TED — Angela Duckworth: Grit — the power of passion and perseverance', 3, 'What did the West Point study find grit predicted?', '[{"label": "A", "text": "Which cadets would score highest on physical fitness tests"}, {"label": "B", "text": "Which cadets would complete the demanding training versus drop out"}, {"label": "C", "text": "Which cadets would be promoted fastest after graduation"}, {"label": "D", "text": "Nothing — the study found grit had no predictive value at West Point"}]'::jsonb, 'B', 'Duckworth cites West Point as one of several settings where grit, not raw talent, predicted who would stick with and complete a demanding program.'),
  ('TED — Angela Duckworth: Grit — the power of passion and perseverance', 4, 'In the Chicago Public Schools study, what did Duckworth find about grittier students, even after controlling for income, test scores, and school safety?', '[{"label": "A", "text": "They were no more likely to graduate than less gritty peers"}, {"label": "B", "text": "They were significantly more likely to graduate high school"}, {"label": "C", "text": "Grit only mattered for students with high test scores"}, {"label": "D", "text": "Grit was found to correlate with lower attendance"}]'::jsonb, 'B', 'This is one of Duckworth''s key pieces of evidence that grit''s predictive power holds even when other, often-assumed factors are controlled for.'),
  ('TED — Angela Duckworth: Grit — the power of passion and perseverance', 5, 'How does Duckworth connect Carol Dweck''s growth-mindset research to grit?', '[{"label": "A", "text": "She argues the two concepts are unrelated"}, {"label": "B", "text": "She cites Dweck''s finding that students who believe the brain can grow through effort are much more likely to persevere after failure, since failure feels temporary rather than permanent — directly supporting persistence"}, {"label": "C", "text": "She argues growth mindset actually reduces grit"}, {"label": "D", "text": "She uses it only as an example of a failed research approach"}]'::jsonb, 'B', 'Duckworth explicitly draws on Dweck''s work to explain a mechanism behind grit: believing ability can grow makes people more willing to keep trying after setbacks.'),
  ('TED — Angela Duckworth: Grit — the power of passion and perseverance', 6, 'What does Duckworth say is still a major open problem in grit research?', '[{"label": "A", "text": "Nothing — she considers the science fully settled"}, {"label": "B", "text": "Science does not yet have well-tested, reliable methods for deliberately building grit in people, and this needs rigorous testing"}, {"label": "C", "text": "Grit cannot be measured at all"}, {"label": "D", "text": "Grit has been proven to be entirely genetic"}]'::jsonb, 'B', 'Duckworth is careful to note that while grit predicts success, the field lacks proven interventions for building it — she calls for more research rather than claiming a solved answer.'),
  ('TED — Angela Duckworth: Grit — the power of passion and perseverance', 7, 'A newer support agent is highly talented technically but gives up on any ticket that isn''t solved within the first attempt, while a less naturally strong agent works stubbornly through multi-day investigations. Per Duckworth''s framework, who is more likely to succeed long-term, and why?', '[{"label": "A", "text": "The technically talented agent, since raw skill always wins over time"}, {"label": "B", "text": "The persistent agent — Duckworth''s research suggests grit (sustained effort toward long-term goals), not raw talent, is what predicts who ultimately succeeds"}, {"label": "C", "text": "Neither — success is unrelated to either trait per her research"}, {"label": "D", "text": "It depends only on which agent has the higher IQ"}]'::jsonb, 'B', 'This mirrors Duckworth''s original classroom observation directly: raw talent without sustained effort underperforms grit in predicting real outcomes.'),
  ('TED — Angela Duckworth: Grit — the power of passion and perseverance', 8, 'A manager wants to help a struggling-but-persistent employee build more grit. Based on the Dweck connection Duckworth draws, what''s a reasonable first step?', '[{"label": "A", "text": "Tell the employee that ability is fixed so they should focus only on their existing strengths"}, {"label": "B", "text": "Help the employee see setbacks as temporary and skill-based (a growth mindset), since Duckworth''s cited research links that belief to greater perseverance after failure"}, {"label": "C", "text": "Avoid mentioning failure at all, since discussing it discourages grit"}, {"label": "D", "text": "Immediately reassign the employee to easier work"}]'::jsonb, 'B', 'Duckworth''s own argument links growth mindset directly to grit — believing failure is temporary and skill-based is what sustains perseverance through it.'),
  ('TED — Angela Duckworth: Grit — the power of passion and perseverance', 9, 'A company wants to select new hires purely by testing raw problem-solving IQ, assuming that predicts long-term performance best. What would Duckworth''s research suggest about this plan?', '[{"label": "A", "text": "It''s well-supported — her research shows IQ is the single best predictor of long-term success"}, {"label": "B", "text": "It risks missing a major factor — her research across West Point, spelling bees, and schools found grit predicted outcomes beyond what IQ alone explained"}, {"label": "C", "text": "IQ and grit are the same thing in her framework, so this is a redundant plan"}, {"label": "D", "text": "Her research found IQ has no relationship at all to any outcome"}]'::jsonb, 'B', 'Duckworth''s whole thesis is that something beyond IQ — grit — is needed to explain who actually succeeds, based on her multiple field studies.'),
  ('TED — Angela Duckworth: Grit — the power of passion and perseverance', 10, 'Why does Duckworth end her talk emphasizing that rigorous testing of grit-building interventions is still needed, rather than offering a guaranteed formula?', '[{"label": "A", "text": "Because she believes grit cannot be taught under any circumstances"}, {"label": "B", "text": "Because she is being intellectually honest about the limits of the evidence — she''s confident grit predicts success, but not yet confident about how to reliably build it, and wants that gap studied rather than glossed over"}, {"label": "C", "text": "Because the talk was originally longer and this part was cut"}, {"label": "D", "text": "Because she disagrees with her own research findings"}]'::jsonb, 'B', 'This closing caveat reflects Duckworth''s scientific caution: strong evidence for what predicts success, honest uncertainty about the best way to intentionally build it.'),
  ('How to Learn: Effective Approaches for Self-Guided Learning', 1, 'What is the course''s central claim about learning?', '[{"label": "A", "text": "Learning happens automatically just by watching or reading content"}, {"label": "B", "text": "Learning is an active process — \"learning is DOING\" — requiring the learner''s participation, not passive consumption"}, {"label": "C", "text": "Learning only occurs in formal classroom settings"}, {"label": "D", "text": "Learning requires no motivation, only access to content"}]'::jsonb, 'B', 'The course explicitly states "learning is DOING" as its central thesis, rejecting passive watching/reading as sufficient on its own.'),
  ('How to Learn: Effective Approaches for Self-Guided Learning', 2, 'What is the first practical step in the course''s learning process, after understanding what learning is?', '[{"label": "A", "text": "Reflection"}, {"label": "B", "text": "Setting learning goals"}, {"label": "C", "text": "Learning with others"}, {"label": "D", "text": "Turning learning into a repeated habit"}]'::jsonb, 'B', 'The curriculum sequence moves from understanding motivation to "Setting Learning Goals" as an early, concrete step, before practice, reflection, and repetition.'),
  ('How to Learn: Effective Approaches for Self-Guided Learning', 3, 'Why does the course include a section on "Reflection"?', '[{"label": "A", "text": "To help learners critically think about the information they received and their progress toward goals, which also boosts motivation"}, {"label": "B", "text": "Reflection is only useful for reviewing test scores"}, {"label": "C", "text": "The course does not include a reflection component"}, {"label": "D", "text": "Reflection replaces the need for practice and application"}]'::jsonb, 'A', 'The course lists two reflection-related objectives: thinking critically about what''s learned, and reflecting on goal progress to boost motivation.'),
  ('How to Learn: Effective Approaches for Self-Guided Learning', 4, 'What is the purpose of the "Learning with Others" section?', '[{"label": "A", "text": "To discourage collaboration in favor of purely independent study"}, {"label": "B", "text": "To plan how to learn with others in order to get help, feedback, and different perspectives"}, {"label": "C", "text": "To replace individual goal-setting entirely"}, {"label": "D", "text": "It focuses solely on competitive learning against peers"}]'::jsonb, 'B', 'The course''s own stated objective for this section is planning collaborative learning specifically to gain help, feedback, and diverse perspectives.'),
  ('How to Learn: Effective Approaches for Self-Guided Learning', 5, 'What is the final stated goal of the course''s overall approach?', '[{"label": "A", "text": "To complete one course and stop"}, {"label": "B", "text": "To turn learning into a lifelong habit (\"Put Learning on Repeat\")"}, {"label": "C", "text": "To only apply the approaches within this specific course, not others"}, {"label": "D", "text": "To eliminate the need for motivation altogether"}]'::jsonb, 'B', 'The final curriculum section, "Put Learning on Repeat," and the course''s closing objective both frame lifelong habitual learning as the ultimate goal.'),
  ('How to Learn: Effective Approaches for Self-Guided Learning', 6, 'Why does the instructor suggest applying this course''s approaches "alongside another course you''re taking"?', '[{"label": "A", "text": "Because this course''s techniques are meta-skills meant to make any other learning experience more effective, not a stand-alone content course"}, {"label": "B", "text": "Because standalone use of this course provides no value"}, {"label": "C", "text": "Because the course requires a paid add-on to use alone"}, {"label": "D", "text": "Because it was designed exclusively for classroom teachers"}]'::jsonb, 'A', 'The course explicitly frames itself as best used alongside other learning, since its content is about how to learn effectively rather than a specific subject.'),
  ('How to Learn: Effective Approaches for Self-Guided Learning', 7, 'A support intern watches every assigned onboarding video start to finish but doesn''t apply any of it to real tickets, expecting to "absorb" the knowledge automatically. Per the course''s framing, why is this an incomplete strategy?', '[{"label": "A", "text": "It''s the ideal strategy — passive watching is sufficient per the course"}, {"label": "B", "text": "The course argues learning is DOING — watching is a step in the right direction but not sufficient on its own; practice and application are required"}, {"label": "C", "text": "Onboarding videos should never be watched at all"}, {"label": "D", "text": "Reflection should replace watching entirely"}]'::jsonb, 'B', 'This is a direct match to the course''s central thesis that watching alone isn''t enough — learning requires active participation like practice and application.'),
  ('How to Learn: Effective Approaches for Self-Guided Learning', 8, 'A new hire sets a learning goal to "get better at GraphQL" but never revisits or reflects on progress toward it. What does the course suggest is missing?', '[{"label": "A", "text": "Nothing is missing; goal-setting alone is sufficient per the course"}, {"label": "B", "text": "Reflection on progress toward the goal — which the course explicitly ties to boosting motivation, not just critical thinking about content"}, {"label": "C", "text": "The goal itself is invalid because it isn''t about factual recall"}, {"label": "D", "text": "The new hire should abandon goal-setting altogether"}]'::jsonb, 'B', 'The course explicitly separates "setting goals" from "reflecting on progress toward goals," treating the latter as a distinct, motivation-boosting step that shouldn''t be skipped.'),
  ('How to Learn: Effective Approaches for Self-Guided Learning', 9, 'Two new hires are both taking the same onboarding course, but one always studies difficult material entirely alone. Per the "Learning with Others" objective, what is this person potentially missing out on?', '[{"label": "A", "text": "Nothing — the course argues solo learning is always superior"}, {"label": "B", "text": "Help, feedback, and different perspectives that come specifically from learning alongside others"}, {"label": "C", "text": "A grade penalty for not collaborating"}, {"label": "D", "text": "The ability to complete the course at all"}]'::jsonb, 'B', 'The course explicitly names help, feedback, and different perspectives as the specific benefits of planning to learn with others — benefits a purely solitary learner would miss.'),
  ('How to Learn: Effective Approaches for Self-Guided Learning', 10, 'Why might a manager use this course''s "learning is DOING" framing when designing onboarding for new support hires?', '[{"label": "A", "text": "To justify skipping all training videos entirely"}, {"label": "B", "text": "To design onboarding that includes practice, application, and reflection steps, not just video-watching, since passive content alone isn''t presented as sufficient for real learning"}, {"label": "C", "text": "The framing has no practical design implications"}, {"label": "D", "text": "To replace all training with unstructured free time"}]'::jsonb, 'B', 'If passive watching alone is insufficient per the course, a manager applying this insight would build in active practice, application, and reflection steps into onboarding design.'),
  ('TED — Julian Treasure: How to speak so that people want to listen', 1, 'Which of these is one of Treasure''s "7 deadly sins of speaking"?', '[{"label": "A", "text": "Gossip — speaking negatively about people who aren''t present"}, {"label": "B", "text": "Asking clarifying questions"}, {"label": "C", "text": "Speaking slowly"}, {"label": "D", "text": "Using silence for emphasis"}]'::jsonb, 'A', 'Gossip is one of the seven habits Treasure identifies as damaging trust and making others want to stop listening to you.'),
  ('TED — Julian Treasure: How to speak so that people want to listen', 2, 'What do the letters in Treasure''s "HAIL" cornerstones stand for?', '[{"label": "A", "text": "Honesty, Ambition, Impact, Leadership"}, {"label": "B", "text": "Honesty, Authenticity, Integrity, Love"}, {"label": "C", "text": "Humor, Attention, Interest, Loyalty"}, {"label": "D", "text": "Hospitality, Awareness, Insight, Longevity"}]'::jsonb, 'B', 'HAIL is Treasure''s mnemonic for the four foundations of powerful, trustworthy speech: honesty, authenticity, integrity, and love (wishing people well).'),
  ('TED — Julian Treasure: How to speak so that people want to listen', 3, 'In Treasure''s "vocal toolbox," what does "register" refer to?', '[{"label": "A", "text": "How fast you speak"}, {"label": "B", "text": "Where your voice resonates from — he recommends speaking from the chest for a more grounded, authoritative sound rather than a nasal or throat register"}, {"label": "C", "text": "The words you choose to use"}, {"label": "D", "text": "How loudly you speak"}]'::jsonb, 'B', 'Register is specifically about vocal resonance/placement in Treasure''s framework, distinct from pace, pitch, or volume.'),
  ('TED — Julian Treasure: How to speak so that people want to listen', 4, 'What does Treasure mean by "prosody" in his vocal toolbox?', '[{"label": "A", "text": "Speaking in a flat monotone for clarity"}, {"label": "B", "text": "The melody and intonation of speech — he warns against monotone delivery because it carries no meaning"}, {"label": "C", "text": "The physical posture you hold while speaking"}, {"label": "D", "text": "The vocabulary level of your speech"}]'::jsonb, 'B', 'Prosody is the up-and-down melody of speech that conveys meaning and emotion; Treasure explicitly warns that monotone delivery loses the listener.'),
  ('TED — Julian Treasure: How to speak so that people want to listen', 5, 'According to Treasure, why is "judging" listed as one of the deadly sins, specifically in the context of listening to others?', '[{"label": "A", "text": "Because judging is always factually incorrect"}, {"label": "B", "text": "Because forming evaluations of someone while they''re speaking blocks you from actually listening to them"}, {"label": "C", "text": "Because judging takes too much time"}, {"label": "D", "text": "Judging is not one of the sins he lists"}]'::jsonb, 'B', 'Treasure frames judging as a listening-blocker: evaluating the speaker in your head crowds out genuinely hearing what they''re saying.'),
  ('TED — Julian Treasure: How to speak so that people want to listen', 6, 'What is the purpose of the vocal warm-up exercises Treasure demonstrates (e.g. "ba-ba-ba", tongue trills, the siren)?', '[{"label": "A", "text": "Purely comedic effect with no practical purpose"}, {"label": "B", "text": "To physically loosen and prepare the voice (lips, tongue, register range) before an important speaking moment"}, {"label": "C", "text": "To help the audience fall asleep"}, {"label": "D", "text": "To test a microphone''s volume levels"}]'::jsonb, 'B', 'Treasure presents these as practical warm-ups — similar to stretching before exercise — to prepare the vocal instrument before speaking.'),
  ('TED — Julian Treasure: How to speak so that people want to listen', 7, 'During a tense customer call, a support agent starts a sentence with "Look, obviously the real problem here is that your team never configured this correctly..." Which deadly sin is this closest to, and what''s the risk?', '[{"label": "A", "text": "Complaining — and the risk is the customer feels blamed rather than helped, which shuts down the conversation"}, {"label": "B", "text": "Judging and, in effect, laying blame — declaring a verdict on the customer''s team rather than staying diagnostic — which risks the customer becoming defensive and disengaging"}, {"label": "C", "text": "Exaggeration — and the only risk is sounding dramatic"}, {"label": "D", "text": "This is a neutral, purely factual statement with no risk"}]'::jsonb, 'B', 'Declaring "the real problem is you did X wrong" is a judgment delivered as fact, which Treasure''s framework flags as something that damages trust and shuts down real listening on the other end.'),
  ('TED — Julian Treasure: How to speak so that people want to listen', 8, 'A support agent wants to sound more credible and calm on customer calls but currently speaks in a flat, unvarying tone regardless of the ticket''s severity. Which element of Treasure''s vocal toolbox should they work on first, and why?', '[{"label": "A", "text": "Volume — because louder always sounds more credible"}, {"label": "B", "text": "Prosody — because varying pitch and melody helps convey urgency, reassurance, or empathy appropriately, instead of sounding the same for every situation"}, {"label": "C", "text": "Timbre — because a warmer voice replaces the need for any vocal variation"}, {"label": "D", "text": "None of the toolbox elements affect how customers perceive a call"}]'::jsonb, 'B', 'A flat, unvarying tone is specifically a prosody problem in Treasure''s framework — the fix is intentional melodic variation to match the message, not simply speaking louder.'),
  ('TED — Julian Treasure: How to speak so that people want to listen', 9, 'A teammate constantly complains in Slack about tickets being "impossible" without proposing next steps. Applying Treasure''s framework, what''s the concern and what would be a better alternative?', '[{"label": "A", "text": "There''s no concern — venting is always healthy and has no effect on others"}, {"label": "B", "text": "Complaining is one of the 7 deadly sins because it spreads negativity (what Treasure calls \"viral misery\") without moving anything forward; a better alternative is naming the specific blocker and what''s needed to resolve it"}, {"label": "C", "text": "The concern is purely about tone of voice, which doesn''t apply to text chat"}, {"label": "D", "text": "The only fix is to stop the teammate from posting in Slack at all"}]'::jsonb, 'B', 'Treasure''s point about complaining is that it spreads negativity without constructive value — the antidote is specific, actionable communication rather than general venting.'),
  ('TED — Julian Treasure: How to speak so that people want to listen', 10, 'Applying the HAIL cornerstones, an agent is asked a question they don''t know the answer to on a live call. Which response best fits HAIL?', '[{"label": "A", "text": "Guess confidently so the customer doesn''t lose trust"}, {"label": "B", "text": "Say honestly \"I don''t know, let me find out and follow up by [time]\" — staying truthful and keeping the commitment, rather than bluffing"}, {"label": "C", "text": "Change the subject to avoid admitting uncertainty"}, {"label": "D", "text": "Blame a previous agent for not documenting the answer"}]'::jsonb, 'B', 'Honesty and integrity (keeping the follow-up commitment) are two of the four HAIL cornerstones — admitting the gap and following through builds more trust than a confident guess that turns out wrong.'),
  ('Time Management Mastery', 1, 'What does the course recommend as the foundation for managing tasks?', '[{"label": "A", "text": "Multiple competing to-do apps used simultaneously"}, {"label": "B", "text": "A single trusted system to collect and manage your tasks"}, {"label": "C", "text": "Memorizing all tasks rather than writing them down"}, {"label": "D", "text": "Relying entirely on a manager to track your tasks"}]'::jsonb, 'B', '"Use your single trusted system to collect and manage your tasks" is an explicit learning objective of the course.'),
  ('Time Management Mastery', 2, 'What does the course teach about using your "natural tendencies and traits"?', '[{"label": "A", "text": "They should be ignored in favor of a universal system"}, {"label": "B", "text": "They should be used to your advantage to optimize your time and productivity"}, {"label": "C", "text": "They are irrelevant to time management"}, {"label": "D", "text": "They only apply to extroverted personality types"}]'::jsonb, 'B', 'The course explicitly teaches using your natural tendencies and traits to your advantage when building your productivity approach.'),
  ('Time Management Mastery', 3, 'What planning horizons does the course explicitly cover?', '[{"label": "A", "text": "Only same-day planning"}, {"label": "B", "text": "Daily, weekly, and long-term work and goals"}, {"label": "C", "text": "Only multi-year planning"}, {"label": "D", "text": "Planning is not covered in this course"}]'::jsonb, 'B', 'The course explicitly lists planning your daily, weekly, and long-term work and goals as a core objective.'),
  ('Time Management Mastery', 4, 'Which techniques does the course name for staying focused on a task?', '[{"label": "A", "text": "Multi-tasking, constant notifications, and open-plan noise"}, {"label": "B", "text": "Single-tasking, time blocking, documentation, and breaks"}, {"label": "C", "text": "Working exclusively at night"}, {"label": "D", "text": "Skipping all breaks to maximize hours worked"}]'::jsonb, 'B', 'The course explicitly names single-tasking, time blocking, documentation, and breaks as focus techniques.'),
  ('Time Management Mastery', 5, 'What is the course''s stated aim regarding work/life boundaries?', '[{"label": "A", "text": "To make work follow you home at all times for maximum output"}, {"label": "B", "text": "To help you \"leave work at work\" and be present at home while still getting everything done"}, {"label": "C", "text": "To eliminate personal time entirely in favor of work"}, {"label": "D", "text": "The course does not address work/life boundaries"}]'::jsonb, 'B', 'The course description explicitly frames leaving work at work, while still getting things done, as a desired outcome.'),
  ('Time Management Mastery', 6, 'What professional background does the instructor draw on to build this course?', '[{"label": "A", "text": "15+ years managing Operations and HR"}, {"label": "B", "text": "A background exclusively in software engineering"}, {"label": "C", "text": "A background exclusively in stand-up comedy"}, {"label": "D", "text": "No professional background is mentioned"}]'::jsonb, 'A', 'The course description explicitly cites the instructor''s 15+ years managing Operations and HR as the basis for the strategies taught.'),
  ('Time Management Mastery', 7, 'A support agent has a personal system for managing tasks but also relies on sticky notes, a phone reminders app, and a notebook simultaneously, leading to missed items. Per the course''s core recommendation, what should change?', '[{"label": "A", "text": "Add a fourth tracking method to be extra safe"}, {"label": "B", "text": "Consolidate to a single trusted system for collecting and managing tasks, per the course''s explicit recommendation"}, {"label": "C", "text": "Abandon all systems and rely purely on memory"}, {"label": "D", "text": "This approach is already ideal per the course"}]'::jsonb, 'B', 'This scenario is a direct violation of the course''s core recommendation to use one single trusted system rather than multiple competing ones.'),
  ('Time Management Mastery', 8, 'A newly promoted team lead is great at daily task management but has no visibility into their goals a month or a quarter out. Which of the course''s planning horizons does this gap map to?', '[{"label": "A", "text": "Long-term planning — the course explicitly separates daily, weekly, and long-term planning as distinct skills"}, {"label": "B", "text": "This gap doesn''t relate to anything the course covers"}, {"label": "C", "text": "Daily planning, which the lead has already mastered"}, {"label": "D", "text": "The course only covers daily planning, so no gap exists"}]'::jsonb, 'A', 'The course explicitly treats long-term planning as a distinct skill alongside daily and weekly planning — exactly the gap described here.'),
  ('Time Management Mastery', 9, 'An agent multitasks between three tickets at once, believing it saves time, but actually finishes all three more slowly with more errors. Which specific technique from the course directly addresses this?', '[{"label": "A", "text": "Single-tasking, which the course names as a technique for more effective focus"}, {"label": "B", "text": "Time blocking has nothing to do with this scenario"}, {"label": "C", "text": "Documentation, since it prevents multitasking entirely on its own"}, {"label": "D", "text": "This scenario isn''t addressed by anything in the course"}]'::jsonb, 'A', 'Single-tasking is explicitly named in the course as a focus technique, directly addressing the multitasking problem in this scenario.'),
  ('Time Management Mastery', 10, 'Why might the course pair "using your natural tendencies" with a "personalized productivity system" rather than prescribing one universal method?', '[{"label": "A", "text": "Because the course argues effective time management should be tailored to the individual, not applied as a rigid, identical system for everyone"}, {"label": "B", "text": "Because personalization contradicts the course''s actual approach"}, {"label": "C", "text": "Because natural tendencies are irrelevant to system design per the course"}, {"label": "D", "text": "Because the course actually recommends one single universal method for all learners"}]'::jsonb, 'A', 'The course explicitly frames building a personalized system around your own tendencies as a core objective, rather than a one-size-fits-all prescription.'),
  ('TED — Kare Anderson: Be an opportunity maker', 1, 'What personal background does Anderson describe as shaping her perspective?', '[{"label": "A", "text": "She grew up as a confident public speaker from a young age"}, {"label": "B", "text": "She was diagnosed as phobically shy and was a stutterer, often feeling invisible or talked around"}, {"label": "C", "text": "She was a professional athlete before her career"}, {"label": "D", "text": "She grew up wealthy with extensive early industry connections"}]'::jsonb, 'B', 'Anderson roots her "opportunity maker" philosophy in her own experience of shyness and stuttering, which shaped how she thinks about connecting with others.'),
  ('TED — Kare Anderson: Be an opportunity maker', 2, 'What does Anderson call the mindset of focusing on bringing people together rather than seeking attention for oneself?', '[{"label": "A", "text": "A \"scarcity mindset\""}, {"label": "B", "text": "A \"mutuality mindset\""}, {"label": "C", "text": "A \"competitive mindset\""}, {"label": "D", "text": "A \"celebrity mindset\""}]'::jsonb, 'B', 'Anderson contrasts self-focused attention-seeking with a "mutuality mindset" that centers on collective benefit and connection.'),
  ('TED — Kare Anderson: Be an opportunity maker', 3, 'How does Anderson describe the ideal reaction to differences between people, for an "opportunity maker"?', '[{"label": "A", "text": "Differences should be minimized or ignored wherever possible"}, {"label": "B", "text": "Being fascinated by differences, rather than affronted by them, which enables collaboration and unexpected outcomes"}, {"label": "C", "text": "Differences should be resolved by having one side adopt the other''s approach"}, {"label": "D", "text": "Anderson argues differences are irrelevant to opportunity-making"}]'::jsonb, 'B', 'Anderson''s framing is that curiosity about differences (not discomfort with them) is what opens the door to valuable, unexpected collaboration.'),
  ('TED — Kare Anderson: Be an opportunity maker', 4, 'What does Anderson say is required to build the kind of relationships that create new opportunities?', '[{"label": "A", "text": "Only networking with people who are similar to you"}, {"label": "B", "text": "Establishing trusted relationships with people who are different, and actively seeking diverse perspectives"}, {"label": "C", "text": "Avoiding new relationships until an opportunity already exists"}, {"label": "D", "text": "Relying solely on formal professional credentials"}]'::jsonb, 'B', 'Anderson emphasizes trust-building specifically across difference as the foundation for the kind of serendipitous opportunities she describes.'),
  ('TED — Kare Anderson: Be an opportunity maker', 5, 'What is the central message of Anderson''s talk?', '[{"label": "A", "text": "People should focus exclusively on developing their own individual talents"}, {"label": "B", "text": "The world needs more people who bring their talents together with others for collective, greater impact than any one person could achieve alone"}, {"label": "C", "text": "Shyness is an insurmountable barrier to professional success"}, {"label": "D", "text": "Opportunities only come to naturally extroverted people"}]'::jsonb, 'B', 'Anderson''s closing thesis is about collective impact through connecting people and talents, not individual achievement alone.'),
  ('TED — Kare Anderson: Be an opportunity maker', 6, 'How does Anderson describe opportunities arising in her framework?', '[{"label": "A", "text": "Purely through formal, planned business meetings"}, {"label": "B", "text": "Serendipitously, through connecting with others around shared interests and action"}, {"label": "C", "text": "Only through paid networking events"}, {"label": "D", "text": "She argues opportunities cannot be intentionally created at all"}]'::jsonb, 'B', 'Anderson frames opportunity-making as emerging from genuine shared interests and action with others, not from rigid formal planning.'),
  ('TED — Kare Anderson: Be an opportunity maker', 7, 'A junior support agent is naturally quiet and worries this limits their career growth. Applying Anderson''s framework, what reframe would be most consistent with her talk?', '[{"label": "A", "text": "Being quiet permanently rules out becoming an opportunity maker"}, {"label": "B", "text": "Shyness doesn''t have to be a barrier — Anderson, despite being phobically shy herself, built her approach around connecting people and mutual benefit rather than self-promotion"}, {"label": "C", "text": "The agent should force themselves to become more outgoing before doing anything else"}, {"label": "D", "text": "Anderson''s talk doesn''t apply to anyone who identifies as shy"}]'::jsonb, 'B', 'Anderson explicitly uses her own shyness and stuttering as the starting point for her opportunity-maker philosophy — it''s a reframe of approach, not a requirement to become extroverted.'),
  ('TED — Kare Anderson: Be an opportunity maker', 8, 'Two engineers on different teams are struggling with similar customer complaints but have never spoken to each other. A support agent connects them over a shared Slack thread, and together they find a fix neither had alone. Which of Anderson''s ideas does this best illustrate?', '[{"label": "A", "text": "Individual achievement is always more valuable than group achievement"}, {"label": "B", "text": "A mutuality mindset — creating value by connecting people around a shared interest, producing an outcome neither could reach alone"}, {"label": "C", "text": "This has nothing to do with Anderson''s talk, since it doesn''t involve strangers"}, {"label": "D", "text": "Opportunity-making only applies to external customer relationships, not internal ones"}]'::jsonb, 'B', 'This is a direct example of the mutuality mindset Anderson describes — someone actively creating value by connecting others rather than focusing only on their own work.'),
  ('TED — Kare Anderson: Be an opportunity maker', 9, 'A new hire wants to build a reputation quickly on the team. Based on Anderson''s approach, which strategy fits her framework best?', '[{"label": "A", "text": "Compete visibly with peers to stand out individually as fast as possible"}, {"label": "B", "text": "Look for chances to connect teammates who could help each other, and build trusted relationships across people who are different from them"}, {"label": "C", "text": "Avoid engaging with anyone outside their immediate team"}, {"label": "D", "text": "Wait passively for opportunities to come without initiating any connections"}]'::jsonb, 'B', 'Anderson''s opportunity-maker approach is specifically about actively connecting people and building relationships across difference, not competing for individual visibility.'),
  ('TED — Kare Anderson: Be an opportunity maker', 10, 'Why does Anderson emphasize her own experience of feeling "invisible" or "talked around" early in the talk?', '[{"label": "A", "text": "It''s an unrelated personal anecdote with no bearing on her argument"}, {"label": "B", "text": "It establishes credibility for her core idea: that people who don''t naturally seek the spotlight can still create outsized impact by focusing on connecting others, rather than needing to overcome shyness first"}, {"label": "C", "text": "It''s meant to discourage shy people from pursuing leadership roles"}, {"label": "D", "text": "It shows that her advice only applies to people who were never shy"}]'::jsonb, 'B', 'Anderson uses her own experience of not being naturally attention-seeking to ground her broader argument that opportunity-making, not self-promotion, is a viable and powerful path for anyone.'),
  ('Customer Service, Customer Support, And Customer Experience', 1, 'How does the course distinguish "Customer Experience" from "Customer Service"?', '[{"label": "A", "text": "They are treated as identical, interchangeable terms"}, {"label": "B", "text": "Customer Experience is the proactive approach to delivering exceptional care; Customer Service is the reactive approach to handling issues as they arise"}, {"label": "C", "text": "Customer Experience only applies to online interactions; Customer Service only applies in-person"}, {"label": "D", "text": "Customer Service is proactive, and Customer Experience is reactive"}]'::jsonb, 'B', 'The course explicitly defines these as two distinct strategies: Experience is proactive (building loyalty from the start), Service is reactive (resolving issues as they come up).'),
  ('Customer Service, Customer Support, And Customer Experience', 2, 'What example does the course give of a proactive Customer Experience touch?', '[{"label": "A", "text": "Resolving an angry customer''s complaint after the fact"}, {"label": "B", "text": "Giving a client something for free on their birthday, to make them feel valued before any issue arises"}, {"label": "C", "text": "Waiting for a customer to complain before taking any action"}, {"label": "D", "text": "Ignoring customer preferences to maintain consistency"}]'::jsonb, 'B', 'The course explicitly uses a birthday gift as an example of proactive Customer Experience — a touch that builds loyalty before any problem occurs.'),
  ('Customer Service, Customer Support, And Customer Experience', 3, 'What does the course claim is the key to turning one-time buyers into loyal "superfans"?', '[{"label": "A", "text": "Leveraging both Customer Experience (proactive) and Customer Service (reactive) together"}, {"label": "B", "text": "Focusing exclusively on Customer Service and ignoring Customer Experience"}, {"label": "C", "text": "Focusing exclusively on Customer Experience and ignoring Customer Service"}, {"label": "D", "text": "Neither strategy has any effect on customer loyalty"}]'::jsonb, 'A', 'The course explicitly frames both strategies together — proactive experience and reactive service — as the "two keys" to building loyal superfans, not either alone.'),
  ('Customer Service, Customer Support, And Customer Experience', 4, 'Per the course, what can excellent customer service do for an "angry and unhappy" customer?', '[{"label": "A", "text": "It can never repair the relationship with an unhappy customer"}, {"label": "B", "text": "It can turn even angry, unhappy customers into loyal clients"}, {"label": "C", "text": "Angry customers should always be deprioritized and ignored"}, {"label": "D", "text": "The course does not address handling upset customers"}]'::jsonb, 'B', 'The course explicitly claims skillful customer service can turn even angry and unhappy customers into loyal, long-term clients.'),
  ('Customer Service, Customer Support, And Customer Experience', 5, 'What emotional/interpersonal qualities does the course emphasize using in customer service?', '[{"label": "A", "text": "Empathy, emotional intelligence, and compassion"}, {"label": "B", "text": "Strict, scripted responses with no personalization"}, {"label": "C", "text": "Indifference to the customer''s emotional state"}, {"label": "D", "text": "Aggressive upselling regardless of the customer''s need"}]'::jsonb, 'A', '"Use empathy, emotional intelligence, and compassion in your customer service" is one of the course''s explicit learning objectives.'),
  ('Customer Service, Customer Support, And Customer Experience', 6, 'Why does the course argue that businesses should focus on delighting current customers, not just chasing new ones?', '[{"label": "A", "text": "Delighted, loyal customers create repeat business and bring friends, effectively becoming a business''s own marketing"}, {"label": "B", "text": "New customers are described as more valuable than existing ones in every case"}, {"label": "C", "text": "The course argues existing customers have no effect on business growth"}, {"label": "D", "text": "This topic is not addressed by the course"}]'::jsonb, 'A', 'The course explicitly argues that thrilling current customers turns them into repeat buyers and referral sources, reducing the need to constantly chase new customers.'),
  ('Customer Service, Customer Support, And Customer Experience', 7, 'A support agent resolves a customer''s complaint competently but does nothing else — no proactive gestures, no anticipation of future needs. Per the course''s two-strategy framework, what''s missing?', '[{"label": "A", "text": "The Customer Experience side — the proactive layer that builds loyalty beyond simply reacting to the complaint"}, {"label": "B", "text": "Nothing is missing; reactive resolution alone fully satisfies the course''s framework"}, {"label": "C", "text": "The Customer Service side, which the agent has also failed to deliver"}, {"label": "D", "text": "Both strategies are irrelevant to this scenario"}]'::jsonb, 'A', 'Competent complaint resolution is the reactive Customer Service piece; the course''s framework argues proactive Customer Experience is a distinct, additional layer needed to build real loyalty.'),
  ('Customer Service, Customer Support, And Customer Experience', 8, 'A customer is furious about a billing error. Per the course''s framing, what''s the potential opportunity in this moment, beyond simply fixing the billing issue?', '[{"label": "A", "text": "The course frames turning angry customers into loyal clients as an explicit possibility through skillful handling of the moment, not just a neutral transaction to close out"}, {"label": "B", "text": "Angry customers should be handled as quickly as possible with no attention to the relationship"}, {"label": "C", "text": "The course argues angry customers can never become loyal again"}, {"label": "D", "text": "This is not addressed in the course"}]'::jsonb, 'A', 'The course explicitly frames turning even angry customers into loyal clients as an achievable outcome of good customer service, not merely damage control.'),
  ('Customer Service, Customer Support, And Customer Experience', 9, 'A company wants to build a proactive loyalty program but is unsure what qualifies. Based on the course''s own example (the birthday gift), which of these best fits the Customer Experience category?', '[{"label": "A", "text": "Sending a personalized note or small gift to a top client for a meaningful occasion, before any problem occurs"}, {"label": "B", "text": "Responding well to a complaint after it''s filed"}, {"label": "C", "text": "Fixing a broken order after the customer reports it"}, {"label": "D", "text": "Issuing a refund only after an escalation"}]'::jsonb, 'A', 'This matches the course''s own example of a proactive Customer Experience touch (the birthday gift) — delivered before any issue, to build the relationship.'),
  ('Customer Service, Customer Support, And Customer Experience', 10, 'Why might a team lead use this course''s Experience/Service distinction when reviewing their team''s customer interactions?', '[{"label": "A", "text": "To check whether the team is only reacting to problems (Service) without also building proactive loyalty (Experience), since the course argues both are needed for lasting loyalty"}, {"label": "B", "text": "The distinction has no practical management use per the course"}, {"label": "C", "text": "To justify only ever doing reactive support work"}, {"label": "D", "text": "To eliminate the need for proactive customer touches entirely"}]'::jsonb, 'A', 'Since the course explicitly argues both proactive Experience and reactive Service are needed together for loyalty, a team lead could use this distinction to spot whether their team is missing the proactive half.')
) as v(title, position, question, options, correct_answer, rationale)
join courses c on c.title = v.title and c.track_id = (select id from tracks where name = 'Core Competency')
on conflict (course_id, position) do nothing;
